/**
 * Экспорт коллекций из БД в seed-collections.ts
 *
 * Запуск:  npx tsx scripts/export-collections.ts
 *           DATABASE_URL=... npx tsx scripts/export-collections.ts
 *
 * Что делает:
 *   1. Подключается к БД (через Prisma, используя DATABASE_URL)
 *   2. Вычитывает все коллекции
 *   3. Генерирует seed-collections.ts с теми же данными
 *   4. Перезаписывает файл целиком
 *
 * Когда использовать:
 *   - После админ-правок, чтобы зафиксировать изменения в репе
 *   - Перед добавлением новых seed-коллекций (чтобы не потерять старые)
 *   - При разворачивании нового окружения
 *
 * Всегда идемпотентен: повторный запуск даёт тот же результат.
 */

import { PrismaClient } from "@prisma/client";
import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const prisma = new PrismaClient();

// Куда писать — перезаписываем seed-collections.ts
const OUTPUT_FILE = path.resolve(__dirname, "../prisma/seed-collections.ts");

// ============================================================
// Типы — дублируем из seed-collections.ts для автогенерации
// ============================================================

interface BookSeed {
  id: string;
  title: string;
  author: string | null;
  coverImageUrl: string;
  description?: string | null;
  thoughts?: string | null;
  genre?: string | null;
  tags?: string[];
  rating?: number;
}

interface CollectionSeed {
  slug: string;
  title: string;
  type: "curated" | "literary";
  categoryId?: string;
  content?: string;
  excerpt?: string;
  coverImageUrl: string;
  bookCovers: string[];
  tags: string[];
  isPublished: boolean;
  order: number;
  editorialNote?: string | null;
  tiers?: Record<string, { id: string; title: string; color: string; bookIds: string[] }>;
  tierOrder?: string[];
  books?: Record<string, BookSeed>;
  unrankedBookIds?: string[];
}

// ============================================================
// Основная функция
// ============================================================

async function main() {
  console.log("🔍 Подключаюсь к БД...");
  const collections = await prisma.collection.findMany({
    orderBy: { order: "asc" },
  });
  console.log(`  Найдено коллекций: ${collections.length}`);

  const seeds: CollectionSeed[] = collections.map((col) => {
    const seed: CollectionSeed = {
      slug: col.slug,
      title: col.title,
      type: col.type as "curated" | "literary",
      categoryId: col.categoryId || undefined,
      content: col.content || undefined,
      excerpt: col.excerpt || undefined,
      coverImageUrl: col.coverImageUrl,
      bookCovers: col.bookCovers as string[],
      tags: col.tags as string[],
      isPublished: col.isPublished,
      order: col.order,
    };

    // Только для curated — добавляем тиры и книги
    if (col.type === "curated") {
      const tiers = col.tiers as Record<string, { id: string; title: string; color: string; bookIds: string[] }> | null;
      const tierOrder = col.tierOrder as string[] | null;
      const books = col.books as Record<string, BookSeed> | null;
      const unrankedBookIds = col.unrankedBookIds as string[] | null;

      if (tiers && Object.keys(tiers).length > 0) {
        seed.tiers = tiers;
      }
      if (tierOrder && tierOrder.length > 0) {
        seed.tierOrder = tierOrder;
      }
      if (books && Object.keys(books).length > 0) {
        seed.books = books;
      }
      if (unrankedBookIds && unrankedBookIds.length > 0) {
        seed.unrankedBookIds = unrankedBookIds;
      }
    }

    // Добавляем editorialNote, если есть (может не быть в схеме пока)
    const note = (col as unknown as Record<string, unknown>).editorialNote as string | null | undefined;
    if (note) {
      seed.editorialNote = note;
    }

    return seed;
  });

  // Генерируем содержимое файла
  const content = generateFileContent(seeds);

  fs.writeFileSync(OUTPUT_FILE, content, "utf-8");
  console.log(`\n✅ Файл записан: ${OUTPUT_FILE}`);
  console.log(`   Коллекций экспортировано: ${seeds.length}`);
}

// ============================================================
// Генератор seed-collections.ts
// ============================================================

function generateFileContent(seeds: CollectionSeed[]): string {
  const lines: string[] = [];

  lines.push(`import { Prisma } from "@prisma/client";`);
  lines.push(``);
  lines.push(`/**`);
  lines.push(` * Seed data for collections.`);
  lines.push(` * Auto-generated by scripts/export-collections.ts`);
  lines.push(` * Редактировать руками, если нужно добавить новые коллекции.`);
  lines.push(` */`);
  lines.push(``);
  lines.push(`type CollectionSeed = {`);
  lines.push(`  slug: string;`);
  lines.push(`  title: string;`);
  lines.push(`  type: "curated" | "literary";`);
  lines.push(`  categoryId?: string;`);
  lines.push(`  content?: string;`);
  lines.push(`  excerpt?: string;`);
  lines.push(`  coverImageUrl: string;`);
  lines.push(`  bookCovers: string[];`);
  lines.push(`  tags: string[];`);
  lines.push(`  isPublished: boolean;`);
  lines.push(`  order: number;`);
  lines.push(`  editorialNote?: string | null;`);
  lines.push(`  tiers?: Record<string, { id: string; title: string; color: string; bookIds: string[] }>;`);
  lines.push(`  tierOrder?: string[];`);
  lines.push(`  books?: Record<string, {`);
  lines.push(`    id: string;`);
  lines.push(`    title: string;`);
  lines.push(`    author: string | null;`);
  lines.push(`    coverImageUrl: string;`);
  lines.push(`    description?: string | null;`);
  lines.push(`    thoughts?: string | null;`);
  lines.push(`    genre?: string | null;`);
  lines.push(`    tags?: string[];`);
  lines.push(`    rating?: number;`);
  lines.push(`  }>;`);
  lines.push(`  unrankedBookIds?: string[];`);
  lines.push(`};`);
  lines.push(``);
  lines.push(`function toPrisma(col: CollectionSeed): Prisma.CollectionCreateInput {`);
  lines.push(`  return {`);
  lines.push(`    slug: col.slug,`);
  lines.push(`    title: col.title,`);
  lines.push(`    type: col.type,`);
  lines.push(`    categoryId: col.categoryId || null,`);
  lines.push(`    content: col.content || null,`);
  lines.push(`    excerpt: col.excerpt || null,`);
  lines.push(`    coverImageUrl: col.coverImageUrl,`);
  lines.push(`    bookCovers: col.bookCovers,`);
  lines.push(`    tags: col.tags,`);
  lines.push(`    isPublished: col.isPublished,`);
  lines.push(`    order: col.order,`);
  lines.push(`    editorialNote: col.editorialNote ?? null,`);
  lines.push(`    tiers: col.tiers as Prisma.InputJsonValue ?? Prisma.JsonNull,`);
  lines.push(`    tierOrder: col.tierOrder || [],`);
  lines.push(`    books: col.books as Prisma.InputJsonValue ?? Prisma.JsonNull,`);
  lines.push(`    unrankedBookIds: col.unrankedBookIds || [],`);
  lines.push(`  };`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`export const collectionSeeds: CollectionSeed[] = [`);

  // Каждая коллекция — отдельный блок
  for (const seed of seeds) {
    lines.push(`  {`);
    lines.push(`    slug: ${JSON.stringify(seed.slug)},`);
    lines.push(`    title: ${JSON.stringify(seed.title)},`);
    lines.push(`    type: ${JSON.stringify(seed.type)},`);
    if (seed.categoryId) {
      lines.push(`    categoryId: ${JSON.stringify(seed.categoryId)},`);
    }
    if (seed.content) {
      lines.push(`    content: \`${escapeTemplateLiteral(seed.content)}\`,`);
    }
    if (seed.excerpt) {
      lines.push(`    excerpt: ${JSON.stringify(seed.excerpt)},`);
    }
    lines.push(`    coverImageUrl: ${JSON.stringify(seed.coverImageUrl)},`);
    lines.push(`    bookCovers: ${JSON.stringify(seed.bookCovers)},`);
    lines.push(`    tags: ${JSON.stringify(seed.tags)},`);
    lines.push(`    isPublished: ${JSON.stringify(seed.isPublished)},`);
    lines.push(`    order: ${seed.order},`);
    if (seed.editorialNote) {
      lines.push(`    editorialNote: ${JSON.stringify(seed.editorialNote)},`);
    }
    if (seed.tiers) {
      lines.push(`    tiers: ${JSON.stringify(seed.tiers)},`);
    }
    if (seed.tierOrder) {
      lines.push(`    tierOrder: ${JSON.stringify(seed.tierOrder)},`);
    }
    if (seed.books) {
      lines.push(`    books: ${JSON.stringify(seed.books)},`);
    }
    if (seed.unrankedBookIds) {
      lines.push(`    unrankedBookIds: ${JSON.stringify(seed.unrankedBookIds)},`);
    }
    lines.push(`  },`);
  }

  lines.push(`];`);
  lines.push(``);
  lines.push(`export function getCollectionSeedData(): Prisma.CollectionCreateInput[] {`);
  lines.push(`  return collectionSeeds.map(toPrisma);`);
  lines.push(`}`);

  return lines.join("\n");
}

/**
 * Экранирование для template literal (backtick-строки).
 * Заменяем `${` и обратные кавычки внутри контента.
 */
function escapeTemplateLiteral(str: string): string {
  return str
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${");
}

// ============================================================
// Запуск
// ============================================================

main()
  .catch((err) => {
    console.error("❌ Ошибка:", err);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
