// ВНИМАНИЕ: проверка через includes(), а не точное совпадение.
// Слова в этом списке нельзя будет использовать ни в каком виде — ни как часть ника.
export const RESERVED_USERNAMES: readonly string[] = [
  // Системные
  "admin",
  "administrator",
  "админ",
  "администратор",
  "moderator",
  "mod",
  "модератор",
  "мод",
  "support",
  "help",
  "поддержка",
  "помощь",
  "info",
  "инфо",
  "информация",
  "feedback",
  "contact",
  "связь",
  "обратная_связь",
  "obratnaya_svyaz",
  "abuse",
  "security",
  "безопасность",
  "sysadmin",
  "system",
  "система",
  "root",
  "superuser",
  "superadmin",
  "суперпользователь",
  "суперадмин",
  "guest",
  "гость",
  "gost",
  "test",
  "testing",
  "тест",
  "тестирование",
  "api",
  "апи",
  "null",
  "undefined",
  "true",
  "false",
  // Служебные разделы
  "pricing",
  "pro",
  "premium",
  "про",
  "премиум",
  "donate",
  "донат",
  "donat",
  "shop",
  "store",
  "магазин",
  "magazin",
  "settings",
  "настройки",
  "nastroiki",
  "profile",
  "профиль",
  "profil",
  "account",
  "аккаунт",
  "akkount",
  "dashboard",
  "дашборд",
  "dashbord",
  "home",
  "дом",
  "search",
  "поиск",
  "poisk",
  "library",
  "библиотека",
  "biblioteka",
  // Социальные
  "team",
  "команда",
  "komanda",
  "official",
  "официальный",
  "officialny",
  "staff",
  "персонал",
  "personal",
  "dev",
  "developer",
  "разработчик",
  "razrabotchik",
  "разраб",
  "razrab",
  "bot",
  "бот",
  "service",
  "сервис",
  "servis",
  "noreply",
  "mailer",
  // Популярные имена, вводящие в заблуждение
  "bookstrata",
  "bookstratapro",
  "strata",
  "tierlist",
  "tiermaker",
  "букстрата",
  "букстратапро",
  "bukstrata",
  "тирлист",
  "tirlist",
  "тирмейкер",
  "tirmeiker",
  "букстраж",
  "bookstrazh",

  // Мат и оскорбления
  "хуй",
  "блядь",
  "пиздец",
  "долбоеб",
  "пидар"
] as const;

export function isReservedUsername(username: string): boolean {
  const normalized = username.toLowerCase();
  return RESERVED_USERNAMES.some((word) => normalized.includes(word));
}
